apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: magic-number
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/pglcorporate-dev/devops-kubernetes-lab1
    targetRevision: main
    path: manifests/magic-number

  destination:
    server: https://kubernetes.default.svc
    namespace: default
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
