name: CD Automated GitOps PR Pattern

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'manifests/magic-number/kustomization.yaml'

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/pglcorporate-dev/magic-number

jobs:
  deploy:
    timeout-minutes: 15
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get SHA tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: apps/magic-number
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}

      - name: Update kustomization.yaml
        run: |
          sed -i "s|newTag: .*|newTag: ${{ steps.vars.outputs.sha_short }}|" manifests/magic-number/kustomization.yaml

      - name: Create GitOps Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: deploy ${{ steps.vars.outputs.sha_short }}"
          title: "Deploy image ${{ steps.vars.outputs.sha_short }}"
          body: |
            Automated deployment PR.

            Image:
            ghcr.io/pglcorporate-dev/magic-number:${{ steps.vars.outputs.sha_short }}

          branch: deploy/${{ steps.vars.outputs.sha_short }}
          delete-branch: true